
-- 1. Create gallery_covers table (For manually setting location covers)
CREATE TABLE IF NOT EXISTS public.gallery_covers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_key TEXT NOT NULL UNIQUE, -- e.g. "Asia/Kabini"
    cover_url TEXT NOT NULL,
    focal_x INTEGER DEFAULT 50,
    focal_y INTEGER DEFAULT 50,
    zoom NUMERIC DEFAULT 1.0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.gallery_covers ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Enable read access for all users" ON public.gallery_covers FOR SELECT USING (true);
-- Allow service role (admin) full access (implicit, but good to note)


-- 2. Create site_stats table (For visit counter)
CREATE TABLE IF NOT EXISTS public.site_stats (
    id TEXT PRIMARY KEY, -- e.g. "main"
    visit_count BIGINT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.site_stats ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Enable read access for all users" ON public.site_stats FOR SELECT USING (true);

-- Insert initial row for site stats
INSERT INTO public.site_stats (id, visit_count)
VALUES ('main', 0)
ON CONFLICT (id) DO NOTHING;
